openapi: 3.1.0
info:
  title: Residential Lending Toolkit API
  description: API for mortgage advisors to assist with client discovery, loan structuring, compliance, refinancing, and credit analysis.
  version: 1.0.0

servers:
  - url: https://api.example.com
    description: Example placeholder server for OpenAI validation

paths:
  /client-discovery:
    post:
      operationId: runClientDiscovery
      summary: Run a client discovery session
      description: Collect personal details, income, expenses, and loan goals.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                clientName:
                  type: string
                contactDetails:
                  type: object
                  properties:
                    email:
                      type: string
                    phone:
                      type: string
      responses:
        '200':
          description: Discovery results
          content:
            application/json:
              schema:
                type: object
                properties:
                  personalInfo:
                    type: object
                  incomeSources:
                    type: array
                    items: { type: string }
                  liabilities:
                    type: array
                    items: { type: string }

  /loan-structuring:
    post:
      operationId: structureGuarantorLoan
      summary: Structure a family guarantor loan
      description: Structure a guarantor or split loan for the client.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                borrowerType:
                  type: string
                guarantorRelationship:
                  type: string
      responses:
        '200':
          description: Structuring details
          content:
            application/json:
              schema:
                type: object
                properties:
                  loanSplit:
                    type: string
                  securityDetails:
                    type: string
                  releaseConditions:
                    type: string

  /document-checklist:
    post:
      operationId: getDocumentChecklist
      summary: List required loan documents
      description: Return required documents based on employment and loan type.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                employmentType:
                  type: string
                loanPurpose:
                  type: string
      responses:
        '200':
          description: Document list
          content:
            application/json:
              schema:
                type: object
                properties:
                  documents:
                    type: array
                    items: { type: string }

  /refinance:
    post:
      operationId: refinanceClient
      summary: Refinance scenario support
      description: Compare post-fixed rate options and retention strategies.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                currentLender:
                  type: string
                fixedRateExpiry:
                  type: string
                  format: date
      responses:
        '200':
          description: Refinancing options
          content:
            application/json:
              schema:
                type: object
                properties:
                  comparisonSummary:
                    type: string
                  breakFees:
                    type: string
                  newOptions:
                    type: array
                    items: { type: string }

  /compliance-bid:
    post:
      operationId: checkComplianceBid
      summary: Generate BID and compliance summary
      description: Generate a BID report and lender comparison for a scenario.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                scenario:
                  type: string
      responses:
        '200':
          description: BID result
          content:
            application/json:
              schema:
                type: object
                properties:
                  bidTemplate:
                    type: string
                  lenderComparison:
                    type: string
                  justificationNotes:
                    type: string

  /first-home-buyer-incentives:
    post:
      operationId: getFhbIncentives
      summary: Return First Home Buyer incentive info
      description: Returns grants and caps for eligible Australian FHBs.
      responses:
        '200':
          description: Incentive info
          content:
            application/json:
              schema:
                type: object
                properties:
                  incentives:
                    type: array
                    items: { type: string }
                  caps:
                    type: string

  /lmi-premium:
    post:
      operationId: estimateLmiPremium
      summary: Estimate LMI premium
      description: Estimate LMI premium based on loan amount and LVR.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lvr:
                  type: number
                loanAmount:
                  type: number
                lender:
                  type: string
      responses:
        '200':
          description: LMI estimate
          content:
            application/json:
              schema:
                type: object
                properties:
                  estimatedPremium:
                    type: number
                  lmiProvider:
                    type: string

  /property-data:
    post:
      operationId: fetchPropertyData
      summary: Retrieve property value and suburb stats
      description: Uses CoreLogic or PriceFinder to get address data.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
      responses:
        '200':
          description: Property data
          content:
            application/json:
              schema:
                type: object
                properties:
                  estimatedValue:
                    type: number
                  recentSales:
                    type: array
                    items: { type: string }
                  suburbStats:
                    type: object

  /rate-comparisons:
    post:
      operationId: getRateComparisons
      summary: Compare interest rates across lenders
      description: Compare live or benchmark interest rates by loan type and LVR.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                loanAmount:
                  type: number
                loanType:
                  type: string
                lvr:
                  type: number
      responses:
        '200':
          description: Rate comparisons
          content:
            application/json:
              schema:
                type: object
                properties:
                  lenderRates:
                    type: array
                    items:
                      type: object
                      properties:
                        lender:
                          type: string
                        rate:
                          type: number
                        comparisonRate:
                          type: number

  /credit-report:
    post:
      operationId: analyzeCreditReport
      summary: Analyze credit report details
      description: Review credit file for risks, score changes, and late payments.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                creditFile:
                  type: object
      responses:
        '200':
          description: Credit report insights
          content:
            application/json:
              schema:
                type: object
                properties:
                  riskFactors:
                    type: array
                    items: { type: string }
                  impactSummary:
                    type: string
